version: '3'
services:
  app:
    image: arpithaoncloud9/my-java-new-app:latestinvali
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: mydbinstance
    ports:
      - "3306:3306"

